USE sakila

INNER JOIN 
SELECT columns
FROM table1
INNER JOIN table2
ON table1.column_name = table2.column_name;


List the number of films per category.
SELECT * FROM film_category

SELECT c.name AS category_name, COUNT(f.film_id) AS film_count
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;


Retrieve the store ID, city, and country for each store.

SHOW FULL TABLES

SELECT * FROM store
SELECT * FROM city
SELECT * FROM country
SELECT * FROM address

SELECT s.store_id, ci.city_id, co.country_id
FROM store s
JOIN address a ON a.address_id = s.address_id
JOIN city ci ON ci.city_id = a.city_id
JOIN country co ON co.country_id = ci.country_id


Calculate the total revenue generated by each store in dollars.

SELECT * FROM store
SELECT * FROM rental
SELECT * FROM payment
SELECT * FROM staff

SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN rental r ON r.staff_id = st.staff_id
JOIN payment p ON p.rental_id = r.rental_id
GROUP BY s.store_id;

Determine the average running time of films for each category.

SELECT * FROM film
SELECT * FROM category
SELECT * FROM film_category

SELECT c.name, AVG(f.length) AS avg_length
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON c.category_id = fc.category_id
GROUP BY c.name;

SHOW FULL TABLES